name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install dependencies and run tests
      - name: Test
        run: |
          npm install
          npm run test

      # Deploy to Render
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl --fail "$DEPLOY_URL"  